/vis/geometry/set/visibility all -1 false
/vis/open OGLIQt
/vis/drawVolume

/vis/geometry/set/forceWireframe all -1 true

/vis/geometry/set/visibility WCBarrelRing    0 true
/vis/geometry/set/visibility WCBarrelAnnulus 0 true
/vis/geometry/set/visibility CapAssembly     0 true
#/vis/geometry/set/visibility WCMultiPMT      0 true

#/vis/geometry/set/forceSolid WCMultiPMT 0 true
#/vis/geometry/set/colour WCMultiPMT 0 1 0 0 1

/Tracking/fractionOpticalPhotonsToDraw 0.1
/vis/scene/add/trajectories
